---
# tasks file for kerberos
- name: install haveged needed to entropy incresing
  get_url:
    url: https://slackware.uk/slackware/slackware64-current/slackware64/a/haveged-1.9.14-x86_64-3.txz
    dest: ./haveged.txz
  delegate_to: 127.0.0.1

- name: unzip the haveged.txz to get the tar
  command: xz ./haveged.txz
  delegate_to: 127.0.0.1
  ignore_errors: yes

- name: copy haveged.tar to remote machine
  copy:
    src: ./haveged.tar
    dest: /root/haveged.tar
    owner: root
    group: root
    mode: 0644

- name: unzip the tar
  unarchive:
    src: /root/haveged.tar
    dest: /root/
    remote_src: true

- name: copy the haveged script into the right directory
  copy:
    src: /root/etc/rc.d/rc.haveged.new 
    dest:  /etc/rc.d/rc.haveged
    owner: root
    group: root
    mode: 0755
    remote_src: true

- name: add the haveged startup script to rc.M to have more entropy on startup
  lineinfile:
    dest: /etc/rc.d/rc.M
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^if [ -x /etc/rc.d/rc.haveged ]; then', line: 'if [ -x /etc/rc.d/rc.haveged ]; then' }
    - { regexp: '^  /etc/rc.d/rc.haveged start', line: '/etc/rc.d/rc.haveged start; fi;' }

- name: trigger the haveged script
  command: /etc/rc.d/rc.haveged start

- name: set kerberosversion
  set_fact:
    krbversion: 1.11.6

- name: download kerberos from web mit edu to control machine (remote does not have internet)
  get_url:
    url: https://web.mit.edu/kerberos/dist/krb5/1.11/krb5-{{krbversion}}-signed.tar
    dest: ./kerberos.tar
  delegate_to: 127.0.0.1

- name: copy kerberos.tar to remote machine
  copy:
    src: ./kerberos.tar
    dest: /root/kerberos.tar
    owner: root
    group: root
    mode: 0644

- name: unzip the kerberos signed tar to get .tar.gz
  unarchive:
    src: /root/kerberos.tar
    dest: /root/
    remote_src: true

- name: unzip the krb5.tar.gz to get the source
  unarchive:
    src: /root/krb5-{{krbversion}}.tar.gz
    dest: /root/
    remote_src: true

- name: configure the krb source
  command: chdir=/root/krb5-{{krbversion}}/src/ ./configure --prefix=/usr --libdir=/usr/lib64 --sysconfdir=/etc --localstatedir=/var/krb5 --datarootdir=/usr/share/krb5

- name: make the krb source
  command: chdir=/root/krb5-{{krbversion}}/src/ make

- name: make install the krb source
  command: chdir=/root/krb5-{{krbversion}}/src/ make install

- name: copy the krb5.conf file
  copy:
    src: "{{ role_path }}/files/krb5.conf"
    dest: /etc/krb5.conf
    owner: root
    group: root
    
- name: Create the logging directory if it does not exist
  file:
    path: /var/log/krb5
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: copy the kadm5.acl file
  copy:
    src: "{{ role_path }}/files/kadm5.acl"
    dest: /etc/kadm5.acl
    owner: root
    group: root

- name: copy the rc.krb5kdc file for service execution
  copy:
    src: "{{ role_path }}/files/rc.krb5kdc"
    dest: /etc/rc.d/rc.krb5kdc
    owner: root
    group: root
    mode: 0755

#- name: start krb5 service
#  command: /etc/rc.d/rc.krb5kdc start

- name: trigger the haveged script restart
  command: /etc/rc.d/rc.haveged restart

#- name: initialise the database
#  command: kdb5_util create -s