---
# tasks file for ftp

- name: download ftp
  get_url:
    url: ftp://ftp.slackware.com/pub/slackware/slackware-10.1/slackware/n/vsftpd-2.0.1-i486-1.tgz
    dest: ./ftp.tgz
  delegate_to: 127.0.0.1

- name: copy ftp.tgz to remote machine
  copy:
    src: ./ftp.tgz
    dest: /root/ftp.tgz
    owner: root
    group: root
    mode: 0644

- name: Create the ftp directory if it does not exist
  file:
    path: /root/ftp
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Extract ftp.tgz into /root/ftp
  unarchive:
    src: ftp.tgz
    dest: /root/ftp


- name: copy the vsftp binaries into /usr/sbin
  copy:
    src: /root/ftp/usr/sbin/
    dest: /usr/sbin/
    mode: 0755
    remote_src: true
    directory_mode: true

- name: copy the ftp home folder into /home
  copy:
    src: /root/ftp/home/
    dest: /home/
    mode: 0755
    remote_src: true
    directory_mode: true

- name: copy the usr share ftp folders into usr share
  copy:
    src: /root/ftp/usr/share/
    dest: /usr/share/
    mode: 0755
    remote_src: true
    directory_mode: true



- name: copy the ftpmessage to ftp homefolder
  copy:
    src: "{{ role_path }}/files/ftpmessage"
    dest: /home/ftp/ftpmessage

- name: copy the vsftp config into /etc
  copy:
    src: /root/ftp/usr/doc/vsftpd-2.0.1/EXAMPLE/INTERNET_SITE_NOINETD/vsftpd.conf
    dest: /etc/vsftpd.conf
    mode: 0755
    remote_src: true


- name: disable anonymous ftp connection
  lineinfile:
    dest: /etc/vsftpd.conf
    regexp: "^anonymous_enable=YES"
    line: "anonymous_enable=NO"

- name: enable local ftp connection
  lineinfile:
    dest: /etc/vsftpd.conf
    regexp: "^local_enable=NO"
    line: "local_enable=YES"

- name: disable oneprocess model
  lineinfile:
    dest: /etc/vsftpd.conf
    regexp: "^one_process_model=YES"
    line: "one_process_model=NO"


- name: Get running vsftpd processes
  shell: "ps -ef | grep -v grep | grep -w vsftpd | awk '{print $2}'"
  register: running_processes

- name: Kill running vsftpd processes
  shell: "kill {{ item }}"
  with_items: "{{ running_processes.stdout_lines }}"

- name: start vsftp
  shell: vsftpd &
  register: vsftpd
  ignore_errors: true

 

    
    #listen=YES