---
# tasks file for ssh
- name: download ssh
  get_url:
    # url: https://slackware.osuosl.org/slackware-14.1/patches/source/openssh/openssh-7.4p1.tar.gz
    url: https://slackbuilds.org/slackbuilds/14.1/network/openssh-krb5.tar.gz
    dest: ./ssh.tar.gz
  delegate_to: 127.0.0.1

- name: download openssl
  get_url:
    url: https://ftp.openssl.org/source/old/1.0.2/openssl-1.0.2.tar.gz
    dest: ./openssl.tar.gz
  delegate_to: 127.0.0.1


- name: copy ssh.tar to remote machine
  copy:
    src: ./ssh.tar.gz
    dest: /root/ssh.tar.gz
    owner: root
    group: root
    mode: 0644

- name: copy openssl.tar to remote machine
  copy:
    src: ./openssl.tar.gz
    dest: /root/openssl.tar.gz
    owner: root
    group: root
    mode: 0644

- name: Create the ssh directory if it does not exist
  file:
    path: /root/ssh
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Create the openssl directory if it does not exist
  file:
    path: /root/openssl
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: unzip ssh tar
  unarchive:
    src: /root/ssh.tar.gz
    dest: /root/ssh
    remote_src: true

- name: unzip openssl tar
  unarchive:
    src: /root/openssl.tar.gz
    dest: /root/openssl
    remote_src: true

- name: configure the openssl source
  command: chdir=/root/openssl/openssl-1.0.2/ ./config

- name: make the openssl source
  command: chdir=/root/openssl/openssl-1.0.2/ make

- name: make install the openssl source
  command: chdir=/root/openssl/openssl-1.0.2/ make install

#- name: configure the ssh source
#  command: chdir=/root/ssh/openssh-7.4p1/ ./configure --with-kerberos5

#- name: make the ssh source
#  command: chdir=/root/ssh/openssh-7.4p1/ make

#- name: make install the ssh source
#  command: chdir=/root/ssh/openssh-7.4p1/ make install

- name: run the SlackBuild
  command: chdir=/root/ssh/openssh-krb5/ sh openssh-krb5.SlackBuild

- name: Create the openssh-krb5 directory if it does not exist
  file:
    path: /root/openssh-krb5
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: unzip openssh-krb5 tar
  unarchive:
    src: /tmp/openssh-krb5-6.7p1-i486-1_SBo.tgz
    dest: /root/openssh-krb5
    remote_src: true

  # /usr/local/sbin/sshd -t -f /usr/local/etc/sshd_config
